- ypkg2/rc.yml
**Variable Macros** (used in the below macros)
- `%python2_version%` returns **2.7** for Python 2.7.x
- `%python3_version%` returns **3.6** for Python 3.6.x
**Actionable Macros** (python unit tests)
`%python_test` and `%python3_test`
If the `PYTHONPATH` environment variable is not set, the macro will do it
The following cases are handled:
1. The macro is called without parameters -> use default test function
e.g.: `%python_test` -> `python setup.py test`
2. The macro is called with a python script (`.py`) as parameter -> execute the script with the specified version of python
e.g.: `%python3_test selftest.py -v` -> `python3 selftest.py -v`
3. The macro is called with something else as parameter -> execute the command "as it is"
e.g.: `%python_test py.test -k 'not this_test'` -> `py.test …
> Python 2+3 version variable and test macros

- ypkg2/rc.yml
This allows calling python with options for example
```    
%python_test -m tornado.test.runtests --verbose
%python3_test -m tornado.test.runtests --verbose
```
Will result in (but also going in the correct location and setting PYTHONPATH)
```    
python2 -m tornado.test.runtests --verbose
python3 -m tornado.test.runtests --verbose
```
Signed-off-by: Pierre-Yves <pyu@riseup.net>
> python_test macros: also support parameters starting with a dash

- ypkg2/rc.yml
The python3_avx2_lib_shift macro will append a .avx2 extension to all python3 .so files in the $installdir. This is intended to be the last command to run as part of the the install step for avx2 builds. This allows a patched python to load the optimized .so.avx2 if a supported cpu is found.
An extra check is added to avx2_lib_shift to ensure it doesn't try and move around files which don't exist. Without this change avx2_lib_shift tries to run automatically after install and would fail for python module avx2 builds.
Generally, this is intended to be good-enough until YPKG3 as I don't want to import too much resources into something which will soon be swapped out. Hopefully for YPKG3 the equivalent of python3_avx2_lib_shift would be able to be run automagically.
> Add python3_avx2_lib_shift macro and and add extra check for avx2_lib_shift

- man/package.yml.5
- man/package.yml.5.html
- man/package.yml.5.md
- ypkg2/ypkgcontext.py
- ypkg2/ypkgspec.py
Identical code folding folds identical functions into a single copy, saving disk space.
Generally useful for large C++ applications.
Only the gold linker can handle icf when using the gcc toolchain, although icf is generally superior when using llvm/lld.
Also add support for function-sections, this is recommended for use with ICF when using gcc/gold but not strictly necessary.
icf-all is not recommended for gcc/gold but is left as an option. icf-all is generally safe for clang/lld due to -faddrsig being default in clang.
Additionally, fix a thinko where runpath wasn't being filtered from cflags/cxxflags.
> Add optional linker flag icf={safe,all} to optimizations

- ypkg2/main.py
This allows us to customize the build for pgo_gen and pgo_use build contexts. E.g. only setting LTO for the pgo_use step.
> Export environmental variables for pgo_gen and pgo_use build contexts

- ypkg2/ypkgcontext.py
GCC's documentation states that by default lto uses 1 job, it can be optionally overridden
with n number of jobs to run in parallel. Pass `-flto=%YJOBS%` when building with GCC LTO to
reduce compilation time.
Clang does not support this and instead uses thin lto for concurrency. Split LTO flags for GCC
and Clang into different variables.
Signed-off-by: Joey Riches <josephriches@gmail.com>
> Ensure LTO for GCC runs in parallel

- ypkg2/rc.yml
Nothing in the repository uses these anymore
> Remove deprecated meson macros

- ybump
Without the parameter "string"s like the summary in a package.yml will get a line break after 80 columns when using "make bump".
This sets the "width"-parameter to '200' to avoid this (thus matching yupdate.py).
I would also be open to setting this even higher if need be.
> Adjust width-param so ybump doesn't set summary to 80 cols

- ypkg2/scripts.py
- ypkg2/ypkgcontext.py
Integrate `sccache`, a compiler cache similar to `ccache` but can also cache Rust builds, particularly those built with the `--release` flag.
Do not merge this until `sccache` has been accepted into the Solus repo (https://dev.getsol.us/D12919).
Signed-off-by: Gavin Zhao <git@gzgz.dev>
> Implement sccache

- ypkg2/ypkgcontext.py
Both GCC and Clang documentation states that instrumentation flags
must be used both when compiling and linking with instrumentation.
Previously some packages failed to build with PGO with errors similar
to this;
undefined reference to `__gcov_time_profiler_counter'
A poor workaround was to add `-lgcov` to LDFLAGS, however, this was much
slower and gave poorer optimization than by simply passing instrumentation
flags to the linker.
It is not neccessary pass PGO use flags to the linker.
This fixes PGO'ing: R, chromium, notepadqq and a bunch of other packages.
Signed-off-by: Joey Riches <josephriches@gmail.com>
> Profile instrumentation flags must also be added to LDFLAGS

- ypkg2/sources.py
This commit allows for renaming of source files by adding `#putNewNameHere.tar.gz` at the end of the source URL. This is useful when multiple of your sources have the same filename, like rocm I am packaging.
There is a complimentary solbuild patch for the same functionality.
> Allow for renaming of simple source files

- ypkg2/compressdoc.py
- ypkg2/main.py
- ypkg2/ui.py
With this, ypkg will compress manpage and info files with gzip at maximum compression. Symlinks will be updated to point to the new compressed files.
When compression has been applied, the output also includes how many files were compressed, and the amount of the space  that was saved by compression.
This has been tested with the `nano` and `xz` packages both with `fakeroot ypkg-build ...` and with `solbuild` after patching Ypkg.
Fixes #30
> Add manpage compression

- yupdate
* Updates `yupdate` to support updating `package.yml`s that are using `git` sources as the url.
* Adds `--yml` argument so that the `if` block at the top of the main function is used.
testing showing `yupdate` checks for `package.yml` existence and that the file must have the extension `.yml`
```
isaac@xps13 ~/packaging/hub $ ../../git/etc/ypkg/yupdate 2.14.2 "git|https://github.com/github/hub.git" --yml does-not-exist.yml
Specified file does not exist
isaac@xps13 ~/packaging/hub $ cp package.{yml,yaml}
isaac@xps13 ~/packaging/hub $ ../../git/etc/ypkg/yupdate 2.14.2 "git|https://github.com/github/hub.git" --yml package.yaml 
package.yaml does not look like a valid package.yml file
```
testing on a repo that uses a `git` source:
```
isaac@xps13 ~/packaging/hub $ pwd …
```
> support updating package.ymls that use git sources

- ypkg2/packages.py
Without the priority bump the files land in the main `32-bit` package instead. See e.g. here: https://dev.getsol.us/R1476:a62f8083e08d340ad527ce359056b809dd0c66b2
> Make sure lib32/cmake/ files get added to 32-bit-devel packages

- ypkg2/rc.yml
Fixes the following warning:
WARNING: Running the setup command as meson \[options\] instead of
meson setup \[options\] is ambiguous and deprecated.
> Update %meson_configure macro to call meson setup

- man/package.yml.5
- man/package.yml.5.html
- man/package.yml.5.md
- man/ypkg-build.1
- man/ypkg-build.1.html
- man/ypkg-install-deps.1
- man/ypkg-install-deps.1.html
- man/ypkg.1
- man/ypkg.1.html
- ypkg2/main.py
- ypkg2/ypkgspec.py
This will only allow $installdir to be used during install and check steps. (Though, packagers should only be using it during install.)
This is extremely desirable due to the extreme overhead of fakeroot. Especially when ccache is enabled but there are no cache hits for a build.
> ypkg2: Only enable fakeroot during the install & check steps

- ypkg2/main.py
ConfigParser is part of the stdlib. Since ypkg is still python2, that means we can drop python2 support for configobj and six.
> main: Use ConfigParser instead of ConfigObj to parse packager config

- ypkg2/rc.yml
Documented by Cabal [here](https://cabal.readthedocs.io/en/3.10/setup-commands.html). The necessary libraries (`Distribution.Simple`) are built with GHC, so this can remove the cyclic dependency where every Haskell package depends on `cabal-install`.
Depends on getsolus/usysconf#12.
> rc: new Haskell macros for Nix-style Cabal builds

- man/package.yml.5
- man/package.yml.5.html
- man/package.yml.5.md
- man/ypkg-build.1
- man/ypkg-build.1.html
- man/ypkg-install-deps.1
- man/ypkg-install-deps.1.html
- man/ypkg.1
- man/ypkg.1.html
- ypkg2/examine.py
- ypkg2/main.py
- ypkg2/packages.py
- ypkg2/rc.yml
- ypkg2/ypkgcontext.py
- Build with march=x86-64-v3 instead of haswell
- Move libs from /usr/lib64/haswell to /usr/lib64/glibc-hwcaps/x86-64-v3
- Drop support for emul32 haswell libs
- Update documentation
> Adjust from legacy to current glibc hwcaps

- man/package.yml.5
- man/package.yml.5.html
- man/package.yml.5.md
- man/ypkg-build.1
- man/ypkg-build.1.html
- man/ypkg-install-deps.1
- man/ypkg-install-deps.1.html
- man/ypkg.1
- man/ypkg.1.html
- ypkg-install-deps
- ypkg2/ypkgspec.py
~~Testing still needed.~~ Tested with `python-packaging` and the checkdeps were installed just as builddeps.
Ideally, we can further improve upon this by emitting a warning if a checkdep appears in the final rundeps or duplicates with a builddep, but that can be put into a separate PR.
Once this is merged, I will add relevant documentation to the help center.
> Add checkdeps field to package.yml

- ybump
- yupdate
This uses the maximum line length to set the output width for the yaml dump in `ybump` and `yupdate`. This avoids having to set a ridiculously large `width` parameter (there is no way to have it accept arbitrary widths).
Without this the scripts mess up formatting for e.g. very long descriptions (or any other line/value longer than 200 characters), which then leads to errors during the package build or other operations.
One could also parse each element of the yaml to find the largest one, but I couldn't quite figure that one out without it getting a bit too complicated
Disadvantage here is that it read the input file twice (once to get the "raw" lines, ones to parse it into a yaml dict). It still happens in the blink of an eye, but it's of course not ideal.
> ybump, yupdate: use max line length of input yaml for output width

- ypkg2/packages.py
These files are created and used by qmake, and are only useful in the devel packages.
> Handle .prl/pri files for qt5/qt6

- ypkg2/dependencies.py
This section of code is supposed to error if the kernel the scanned module is dependent against cannot be found. Instead it panicked likely due to a bad copy and paste.
> Fix panic in kernel analysis

- ypkg2/packages.py
This removes the old pattern of `/usr/share/man3/` for the -devel package. This folder isn't used by a single package in the repo, and I assume was meant to be `/usr/share/man/man3` which was added later.
(or the MANPATH was changed at some point?)
> Remove old, wrong man3 pattern

- ypkg2/rc.yml
For setup, build, install and check steps respectively.
> rc.yml: Provide cargo_{fetch,build,install,test} macros

- ypkg2/rc.yml
Prefer Makefile.PL in the perl macros to support current build standards
Fixes getsolus/ypkg/issues/65
> perl macros: Update to check for Makefile.PL first

- TESTING.md
- prepare_ypkg_test_venv.sh
- ypkg2/packages.py
`self.add_pattern("/usr/lib32/", "32bit")` 
defined earlier seems to be overriding these patterns since the py3 port, so increase the priority by one to fixor.
`self.add_pattern("/usr/lib32/lib*.so.*", "32bit"` 
has been removed as it is already defined earlier in the patterns as:
`self.add_pattern("/usr/lib32/lib*.so.*", "32bit",
priority=PRIORITY_DEFAULT+1)`
so it looks like this problem has cropped up before.
> ypkg2/packages: Fix patterns for 32bit-devel subpackages

- ypkg2/rc.yml
This adds the %symlink_check macro to look for and exit on finding broken symlinks.
Exporting SYMLINK_WARN will make it just print the broken symlinks and warning message without halting the package build.
> Add macro to check for broken symlinks in installdir

- ypkg2/metadata.py
Our system iksemel escapes unicode to work around py2 emoji parsing errors. Add files from pre-escaped files.list instead of pkg.files.list to fix creating .eopkgs with unicode paths.
(issue was found in usdx and it contains Ä, Ö, and, Ü characters in the filepaths)
> metadata: Do not use escaped file paths when creating package

- requirements.txt
- ypkg2/__init__.py
- ypkg2/examine.py
- ypkg2/metadata.py
Brought back another old commit. Depends on getsolus/eopkg#57 (ypkg will exit with an exception if it imports eopkg without that commit). Has the same limitation regarding nuitka as is mentioned in that PR.
Note that this xattr support intentionally only supports executables for now since we basically only care about the `security.capability` attribute for file capabilities.
This was tested by building packages that both do and do not contain file caps, and installing them with py2 eopkg (no patch applied, so it's unaware of the new fields) and with py3 eopkg (with patch applied so it correctly applies the attributes).
> Export xattrs info to files.xml internally in our eopkg

- ybump
- yupdate
The API for ruamel changed in version 0.18 and the old entry functions have been removed. See https://yaml.readthedocs.io/en/latest/api/
The old loading and dumping methods in `ybump` and `yauto` thus no longer work. This updates them to the new API.
> ybump/yupdate: Adjust to ruamel 0.18 API

- ypkg2/examine.py
- ypkg2/ypkgcontext.py
LTO Bytecode is non portable. Let's build everything with fat lto objects then strip the bytecode after the fact.
Note: only clang 18 supports fat lto objects
> Build with fat LTO objects by default and strip LTO bytecode from static archives

- ypkg2/rc.yml
- Keep debug info now dwarf 5 is properly supported
- use non-deprecated options
- enable peephole and frame-opt optimizations
> rc.yml: Update bolt optimization flags

- ypkg2/scripts.py
- ypkg2/ypkgcontext.py
> rust: Add RUSTFLAGS

- yupdate
If additional sources exist don't nuke them. This is the behaviour we want the vast majority of the time.
test case: `yupdate  24.06.0 https://poppler.freedesktop.org/poppler-24.06.0.tar.xz`
before
```diff
diff --git a/packages/p/poppler/package.yml b/packages/p/poppler/package.yml
index 2ef4d4047b..67c08f43af 100644
--- a/packages/p/poppler/package.yml
+++ b/packages/p/poppler/package.yml
@@ -1,9 +1,8 @@
name       : poppler
-version    : 24.04.0
-release    : 49
+version    : 24.06.0
+release    : 50
source     :
-    - https://poppler.freedesktop.org/poppler-24.04.0.tar.xz : 1e804ec565acf7126eb2e9bb3b56422ab2039f7e05863a5dfabdd1ffd1bb77a7
-    - git|https://gitlab.freedesktop.org/poppler/test.git : 400f3ff05b2b1c0ae17797a0bd50e75e35c1f1b1
+    - …
```
> yupdate: Only update the first element in list

- ypkg2/rc.yml
This allows multiple arguments to the %cargo_install macro, in case there are several binaries to install
Resolves https://github.com/getsolus/packages/issues/3230
> Allow multiple arguments to %cargo_install

- ypkg
- ypkg2/main.py
- ypkg2/ypkgcontext.py
Allow packager's to override the default build output directory.
This in primarily intended for solbuild to invoke ypkg-build as root but continue to use the 'build' user directories.
> ypkg: Allow a custom build directory

- ypkg-install-deps
Previously, it silently defaulted to eopkg (= eopkg.py2 at the time of this writing).
It now defaults to 'eopkg.py3'.
> ypkg-install-deps: Add -e/--eopkg-cmd argument

- ypkg2/rc.yml
Noticed while trying to package an `anoise` update that had a main folder called "anoise "
With this patch it builds successfully without renaming
> Make Python macros work for directories with spaces in them

- ypkg2/examine.py
Binutils update https://github.com/getsolus/packages/commit/ddf491a97c28416ea78c9b8f06cfd505dfb92cb5#diff-5f5bc0944056a92ed60811fab1f7d27b2d22e52b93ad867505b0169d485336f1R71 added the `--enable-new-dtags` argument which changed ld so that `RUNPATH` was used instead of `RPATH` (this is a beneficial change for reasons I won't go into here). Unfortunately ypkg only checked for `RPATH` which broke automatic dependency detection when using `RPATH`/`RUNPATH`.
Fix this in ypkg by checking the `readelf` output for `RUNPATH` as well.
Note that this will probably also fix a few other packages that had `Fatal: Unknown symbol` errors (which aren't actually fatal BTW).
> examine: Fix runpath detection

- ypkg2/rc.yml
The weird workdir managling causes more issues than it solves so remove it
python3 setup.py test no longer works as a generic entry point with newer versions of setuptools so adjust it.
> rc.yml: Python3 macro adjustments

- ypkg2/rc.yml
This can be requied in the case of avx2 build for example where we want to overwrite the avx2 built files with the x86_64 built ones after the avx2 files have been moved to the right place.
> rc.yml: Pass --overwrite-existing to the python installer module

- ypkg2/main.py
Resolves inability to read packager file:
```
[Config] Error in packager config:
'ConfigParser' object has no attribute 'readfp'
[Config] Using default packager values
```
>configparser.ConfigParser no longer has a readfp method. Use read_file() instead.
https://docs.python.org/3/whatsnew/3.12.html
> Switch from readfp to read_file

- data/macros/actions/cargo.yaml
This adds macros for `%cargo_cbuild` and `%cargo_cinstall`.
While I was in the area, I added some definitions to make the Cargo macros easier to work with, similar to AerynOS's Cargo macros.
Fixes https://github.com/getsolus/ypkg/issues/97
- Copy `data/macros/actions` to `/usr/share/ypkg/macros/actions`
- Install `cargo-c`, and build the `rav1e` package, after modifying it to use the new macros.
> macros: Add cargo_cbuild and cargo_cinstall macros
